apiVersion: v1
kind: Service
metadata:
  name: adds-azure-mcp-agent-service
spec:
  selector:
    app: adds-azure-mcp-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
